import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata:Metadata={title:"Privacy — Instruxa",description:"How Instruxa handles account, prompt, provider-key, usage, and billing data during private beta."};

export default function PrivacyPage(){return <LegalPage eyebrow="PRIVACY" title="Privacy practices" summary="A clear account of what Instruxa processes, why it is needed, and the controls protecting your workspace." sections={[
 {title:"Information we process",content:<><p>Instruxa processes the name and email address you provide, a derived password hash, session records, saved prompt projects, model responses, evaluation results, and usage metadata required to operate your account.</p><p>When you use bring-your-own-key access, the provider key is encrypted before storage. Only its final four characters are retained separately for identification.</p></>},
 {title:"How information is used",content:<ul><li>Authenticate your account and protect private workspace data.</li><li>Compile, execute, store, compare, and evaluate prompts at your direction.</li><li>Measure credits, tokens, latency, reliability, and product performance.</li><li>Prevent abuse, investigate failures, and improve service security.</li><li>Maintain subscription and credit records when billing is activated.</li></ul>},
 {title:"AI providers and subprocessors",content:<><p>Model requests are sent to the provider selected by the user: OpenAI, Anthropic, or Google Gemini. Provider processing is governed by that provider&apos;s terms and data practices.</p><p>Cloudflare provides edge runtime and D1 persistence. Stripe is the intended billing processor; Instruxa does not store complete card details. Live billing is not active during the current preview.</p></>},
 {title:"Retention and deletion",content:<><p>Projects, runs, encrypted keys, usage, and billing records remain associated with the account while required to provide the service, meet security needs, or satisfy applicable obligations. Individual projects, runs, and connected provider keys can be removed through supported product controls.</p><p>Formal account deletion and automated retention controls remain launch requirements and will be documented before paid public availability.</p></>},
 {title:"Your choices",content:<ul><li>Use BYOK or avoid connecting a provider key.</li><li>Delete saved projects, run history, and connected provider keys using available controls.</li><li>Avoid placing sensitive personal data in prompts unless it is necessary and permitted.</li><li>Contact the repository owner privately for access or deletion requests during beta.</li></ul>},
 {title:"Security and contact",content:<p>Security reports and privacy requests must not include passwords, API keys, session cookies, private prompts, or payment information. Use the private reporting guidance in the <a href="https://github.com/veerendrakalyanbabu-VKB/Instruxa/blob/main/SECURITY.md">Instruxa Security Policy</a>.</p>},
 ]}/>}
