"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, Braces, Building2, ChevronRight, Clipboard, Code2, Command, Cpu, Gauge, GitBranch, KeyRound, Layers3, Menu, ShieldCheck, Sparkles, Users, WandSparkles, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AccountWorkspace } from "@/components/account-workspace";
import { ModelRunner } from "@/components/model-runner";
import { UsageDashboard } from "@/components/usage-dashboard";
import { BillingCenter } from "@/components/billing-center";

const templates = [
  [Code2,"Code architect","Design a production-ready API for a multi-tenant SaaS application"],
  [Building2,"Strategy brief","Create a go-to-market plan for a developer tooling startup"],
  [Braces,"Structured extraction","Extract contracts into a validated JSON schema with citations"],
] as const;
export default function Home(){
 const [goal,setGoal]=useState("Design a production-ready API for a multi-tenant SaaS application"); const [audience,setAudience]=useState("Senior backend engineers"); const [tone,setTone]=useState("Precise & technical"); const [model,setModel]=useState("Universal"); const [copied,setCopied]=useState(false); const [menu,setMenu]=useState(false);
 const prompt=useMemo(()=>`# Role\nYou are a principal AI systems architect with deep experience shipping secure, observable production systems.\n\n# Objective\n${goal.trim()||"Describe the desired outcome"}.\n\n# Audience\nWrite for ${audience||"a technical product team"}. Use a ${tone.toLowerCase()} communication style.\n\n# Requirements\n- Clarify assumptions before making irreversible design choices.\n- Provide the architecture, data flow, failure modes, and security boundaries.\n- Separate MVP requirements from scale-stage improvements.\n- Include concrete implementation examples where they improve precision.\n- Call out tradeoffs, risks, and validation criteria.\n\n# Output contract\n1. Executive summary\n2. Architecture and component responsibilities\n3. Implementation sequence\n4. Security and reliability checklist\n5. Acceptance tests\n\n# Quality bar\nThe response must be actionable, internally consistent, and free of invented facts. If required information is missing, state the uncertainty explicitly.`,[goal,audience,tone]);
 async function copy(){await navigator.clipboard?.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 function loadProject(project:{goal:string;audience:string;tone:string;model:string}){setGoal(project.goal);setAudience(project.audience);setTone(project.tone);setModel(project.model)}
 return <main className="min-h-screen overflow-hidden bg-[#060609] text-white"><div className="noise"/><div className="aurora"/><div className="grid-field"/>
  <nav className="nav-shell"><a href="#" className="flex items-center gap-2.5 font-semibold"><span className="logo"><Command size={18}/></span><span className="text-xl tracking-[-.03em]">Instruxa</span><Badge className="beta">PRIVATE BETA</Badge></a><div className="hidden gap-1 text-sm text-zinc-400 md:flex"><a className="nav-link" href="#studio">Product</a><a className="nav-link" href="#capabilities">Solutions</a><a className="nav-link" href="#billing">Pricing</a><a className="nav-link" href="https://github.com/veerendrakalyanbabu-VKB/Instruxa#readme">Docs</a></div><div className="hidden gap-3 md:flex"><Button asChild variant="ghost" className="text-zinc-400 hover:text-white"><a href="#account">Sign in</a></Button><Button asChild className="glow"><a href="#studio">Start building <ArrowRight size={15}/></a></Button></div><Button aria-label={menu?"Close navigation":"Open navigation"} variant="ghost" size="icon" className="md:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></nav>
  {menu&&<div className="relative z-30 mx-5 grid gap-2 rounded-2xl border border-white/10 bg-zinc-950 p-4 md:hidden"><a className="p-2" href="#studio">Product</a><a className="p-2" href="#billing">Pricing</a><a className="p-2" href="#account">Account</a><Button asChild><a href="#studio">Start building</a></Button></div>}
  <section className="hero"><div className="orb"/><Badge variant="outline" className="hero-badge"><span className="status-dot"/><Sparkles size={12}/> Instruxa intelligence engine is online <ChevronRight size={12}/></Badge><h1>Engineering-grade prompts.<br/><span className="gradient">Built at the speed of thought.</span></h1><p>One precision workspace to design, optimize, evaluate, and govern the instructions powering your AI products.</p><div className="hero-actions"><Button size="lg" className="glow h-12 px-6" onClick={()=>document.getElementById("studio")?.scrollIntoView({behavior:"smooth"})}>Enter the workspace <ArrowRight size={16}/></Button><Button size="lg" variant="outline" className="ghost-button" onClick={()=>document.getElementById("model-runner")?.scrollIntoView({behavior:"smooth"})}><span className="play-dot">▶</span> Explore live AI workflow</Button></div><div className="proof-row">{([[ShieldCheck,"Security-first"],[Gauge,"Performance-first"],[KeyRound,"BYOK encrypted"],[GitBranch,"Version controlled"]] as const).map(([Icon,label])=><span key={label}><Icon size={13}/>{label}</span>)}</div></section>
  <section id="studio" className="studio-section"><div className="floating-pill pill-a"><Activity size={12}/> Live quality analysis</div><div className="floating-pill pill-b"><Cpu size={12}/> 4 model targets</div><div className="studio"><div className="scan-line"/><header className="studio-header"><div className="window-controls"><i/><i/><i/></div><div className="flex items-center gap-3"><span className="compiler-icon"><WandSparkles size={16}/></span><div><h2 className="text-sm font-medium">Prompt Compiler</h2><p className="text-xs text-zinc-500">Untitled project · Draft saved</p></div></div><div className="ml-auto flex items-center gap-2"><span className="hidden items-center gap-1.5 text-[10px] text-emerald-400 sm:flex"><span className="status-dot"/> SYSTEM READY</span><Select value={model} onValueChange={setModel}><SelectTrigger className="h-8 w-[145px] border-white/10 bg-white/[.03] text-xs"><SelectValue/></SelectTrigger><SelectContent>{["Universal","OpenAI","Claude","Gemini"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></header>
  <div className="grid lg:grid-cols-2"><div className="border-b border-white/[.07] p-5 lg:border-b-0 lg:border-r lg:p-7"><span className="label">01 · DESCRIBE THE OUTCOME</span><Textarea aria-label="Desired prompt outcome" value={goal} onChange={e=>setGoal(e.target.value)} className="mt-4 min-h-32 resize-none border-white/10 bg-black/20 text-base leading-7"/><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-xs text-zinc-500">Audience<Input value={audience} onChange={e=>setAudience(e.target.value)} className="border-white/10 bg-white/[.025]"/></label><label className="grid gap-2 text-xs text-zinc-500">Response style<Select value={tone} onValueChange={setTone}><SelectTrigger className="border-white/10 bg-white/[.025]"><SelectValue/></SelectTrigger><SelectContent>{["Precise & technical","Concise & executive","Clear & educational"].map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></label></div><div className="mt-6"><span className="label">QUICK STARTS</span><div className="mt-3 grid gap-2">{templates.map(([Icon,name,text])=><button key={name} onClick={()=>setGoal(text)} className="template"><Icon size={15}/><span>{name}</span><ArrowRight size={13} className="ml-auto"/></button>)}</div></div><Button className="glow mt-6 h-11 w-full" onClick={()=>document.getElementById("output")?.scrollIntoView({behavior:"smooth",block:"center"})}><Sparkles size={15}/> Compile prompt</Button></div>
  <div id="output" className="output-panel"><div className="mb-4 flex items-center justify-between"><span className="label">02 · COMPILED PROMPT</span><div className="flex items-center gap-2"><div className="quality"><span>94</span><i>quality</i></div><Button size="sm" variant="ghost" className="text-xs text-zinc-400" onClick={copy}><Clipboard size={13}/>{copied?"Copied":"Copy"}</Button></div></div><div className="output"><div className="code-rail">{Array.from({length:18},(_,i)=><span key={i}>{i+1}</span>)}</div><pre>{prompt}</pre></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-[10px] text-zinc-500">{[["Clear","objective"],["5","constraints"],[model,"target"]].map(([a,b])=><div className="metric" key={b}><strong>{a}</strong><span>{b}</span></div>)}</div></div></div></div></section>
  <AccountWorkspace draft={{goal,audience,tone,model,compiledPrompt:prompt}} onLoad={loadProject}/>
  <ModelRunner prompt={prompt}/>
  <UsageDashboard/>
  <BillingCenter/>
  <section id="capabilities" className="border-y border-white/[.06] bg-white/[.018] py-24"><div className="mx-auto max-w-[1180px] px-5"><div className="mb-14 max-w-2xl"><span className="eyebrow">BUILT FOR AI DELIVERY</span><h2 className="mt-4 text-4xl font-medium tracking-tight sm:text-5xl">From idea to measurable AI asset.</h2><p className="mt-5 text-zinc-400">Instruxa treats prompts like production code: structured, measurable, portable, and ready to evolve.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.08] md:grid-cols-3">{([[Layers3,"Compile, don’t guess","Turn goals, context and constraints into a complete instruction system."],[Zap,"Model-aware optimization","Prepare prompts for every major model without rewriting from scratch."],[ShieldCheck,"Security foundations","Account ownership, protected sessions, encrypted BYOK, and private run history."],[KeyRound,"Hybrid model access","Use included credits or connect provider keys for control and scale."],[Users,"Response intelligence","Compare models, score responses, select winners, and track performance over time."],[Command,"Developer-first exports","Copy clean Markdown and export complete model responses for downstream work."]] as const).map(([Icon,title,body])=><article className="feature" key={title}><Icon size={21}/><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-[1180px] px-5 pb-28"><div className="cta"><div><span className="eyebrow">READY TO BUILD BETTER?</span><h2 className="mt-3 text-3xl font-medium sm:text-4xl">Make every AI interaction intentional.</h2></div><Button size="lg" className="glow" onClick={()=>document.getElementById("account")?.scrollIntoView({behavior:"smooth"})}>Start building free <ArrowRight size={16}/></Button></div></section><footer className="border-t border-white/[.06]"><div className="mx-auto flex max-w-[1180px] flex-col gap-5 px-5 py-8 text-xs text-zinc-600 sm:flex-row sm:justify-between"><span className="text-zinc-400">Instruxa</span><p>© 2026 Instruxa. Prompt infrastructure for ambitious teams.</p><div className="flex gap-5"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/security">Security</Link></div></div></footer>
 </main>
}
