"use client";
import { useMemo, useState } from "react";
import { ArrowRight, Braces, Building2, Check, Clipboard, Code2, Command, KeyRound, Layers3, Menu, ShieldCheck, Sparkles, Users, WandSparkles, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const templates = [
  [Code2,"Code architect","Design a production-ready API for a multi-tenant SaaS application"],
  [Building2,"Strategy brief","Create a go-to-market plan for a developer tooling startup"],
  [Braces,"Structured extraction","Extract contracts into a validated JSON schema with citations"],
] as const;
const plans = [
  ["Free","$0","Explore the workflow",["25 compilations / month","Bring your own API key","3 private projects","Community templates"]],
  ["Pro","$19","For individual builders",["1,000 included credits / month","BYOK with zero markup","Unlimited projects & versions","Prompt quality scoring"]],
  ["Team","$49","Per workspace / month",["5 team members included","5,000 shared credits / month","Roles, approvals & audit log","Shared prompt registry"]],
  ["Enterprise","Custom","Security and scale",["SSO/SAML and SCIM","Private model gateways","Custom retention policies","SLA and onboarding"]],
] as const;

export default function Home(){
 const [goal,setGoal]=useState("Design a production-ready API for a multi-tenant SaaS application"); const [audience,setAudience]=useState("Senior backend engineers"); const [tone,setTone]=useState("Precise & technical"); const [model,setModel]=useState("Universal"); const [copied,setCopied]=useState(false); const [menu,setMenu]=useState(false);
 const prompt=useMemo(()=>`# Role\nYou are a principal AI systems architect with deep experience shipping secure, observable production systems.\n\n# Objective\n${goal.trim()||"Describe the desired outcome"}.\n\n# Audience\nWrite for ${audience||"a technical product team"}. Use a ${tone.toLowerCase()} communication style.\n\n# Requirements\n- Clarify assumptions before making irreversible design choices.\n- Provide the architecture, data flow, failure modes, and security boundaries.\n- Separate MVP requirements from scale-stage improvements.\n- Include concrete implementation examples where they improve precision.\n- Call out tradeoffs, risks, and validation criteria.\n\n# Output contract\n1. Executive summary\n2. Architecture and component responsibilities\n3. Implementation sequence\n4. Security and reliability checklist\n5. Acceptance tests\n\n# Quality bar\nThe response must be actionable, internally consistent, and free of invented facts. If required information is missing, state the uncertainty explicitly.`,[goal,audience,tone]);
 async function copy(){await navigator.clipboard?.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 return <main className="min-h-screen overflow-hidden bg-[#07070a] text-white"><div className="noise"/>
  <nav className="relative z-30 mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 lg:px-10"><a href="#" className="flex items-center gap-2.5 font-semibold"><span className="logo"><Command size={18}/></span><span className="text-xl">Instruxa</span><Badge className="border-white/10 bg-white/5 text-[10px] text-zinc-400">BETA</Badge></a><div className="hidden gap-8 text-sm text-zinc-400 md:flex"><a href="#studio">Product</a><a href="#capabilities">Solutions</a><a href="#pricing">Pricing</a><a href="#">Docs</a></div><div className="hidden gap-3 md:flex"><Button variant="ghost">Sign in</Button><Button className="glow">Start building <ArrowRight size={15}/></Button></div><Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></nav>
  {menu&&<div className="relative z-30 mx-5 grid gap-2 rounded-2xl border border-white/10 bg-zinc-950 p-4 md:hidden"><a className="p-2" href="#studio">Product</a><a className="p-2" href="#pricing">Pricing</a><Button>Start building</Button></div>}
  <section className="relative mx-auto max-w-[1440px] px-5 pb-20 pt-16 text-center lg:pt-24"><div className="orb"/><Badge variant="outline" className="mb-7 border-violet-400/20 bg-violet-400/5 px-3 py-1.5 text-violet-200"><Sparkles size={13} className="mr-2"/> The prompt engineering workspace for serious AI teams</Badge><h1 className="mx-auto max-w-5xl text-balance text-5xl font-medium leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[92px]">Turn intent into<br/><span className="gradient">production-grade prompts.</span></h1><p className="mx-auto mt-7 max-w-2xl text-pretty text-base leading-7 text-zinc-400 sm:text-lg">Design, improve, test, version, and ship reliable AI instructions from one intelligent workspace—across every major model.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button size="lg" className="glow h-12 px-6" onClick={()=>document.getElementById("studio")?.scrollIntoView({behavior:"smooth"})}>Build your first prompt <ArrowRight size={16}/></Button><Button size="lg" variant="outline" className="h-12 border-white/10 bg-white/[.03] px-6 text-zinc-200">See how it works</Button></div><div className="mt-10 flex flex-wrap justify-center gap-6 text-xs text-zinc-500">{["No credit card","BYOK supported","Export anywhere"].map(x=><span className="flex items-center gap-1.5" key={x}><Check size={13} className="text-emerald-400"/>{x}</span>)}</div></section>
  <section id="studio" className="mx-auto max-w-[1240px] px-4 pb-28"><div className="studio"><header className="flex flex-col gap-3 border-b border-white/[.07] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet-500/15 text-violet-300"><WandSparkles size={16}/></span><div><h2 className="text-sm font-medium">Prompt Compiler</h2><p className="text-xs text-zinc-500">Transform rough intent into a reliable instruction</p></div></div><Select value={model} onValueChange={setModel}><SelectTrigger className="h-8 w-[150px] border-white/10 bg-white/[.03] text-xs"><SelectValue/></SelectTrigger><SelectContent>{["Universal","OpenAI","Claude","Gemini"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></header>
  <div className="grid lg:grid-cols-2"><div className="border-b border-white/[.07] p-5 lg:border-b-0 lg:border-r lg:p-7"><span className="label">01 · DESCRIBE THE OUTCOME</span><Textarea value={goal} onChange={e=>setGoal(e.target.value)} className="mt-4 min-h-32 resize-none border-white/10 bg-black/20 text-base leading-7"/><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-xs text-zinc-500">Audience<Input value={audience} onChange={e=>setAudience(e.target.value)} className="border-white/10 bg-white/[.025]"/></label><label className="grid gap-2 text-xs text-zinc-500">Response style<Select value={tone} onValueChange={setTone}><SelectTrigger className="border-white/10 bg-white/[.025]"><SelectValue/></SelectTrigger><SelectContent>{["Precise & technical","Concise & executive","Clear & educational"].map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></label></div><div className="mt-6"><span className="label">QUICK STARTS</span><div className="mt-3 grid gap-2">{templates.map(([Icon,name,text])=><button key={name} onClick={()=>setGoal(text)} className="template"><Icon size={15}/><span>{name}</span><ArrowRight size={13} className="ml-auto"/></button>)}</div></div><Button className="glow mt-6 h-11 w-full" onClick={()=>document.getElementById("output")?.scrollIntoView({behavior:"smooth",block:"center"})}><Sparkles size={15}/> Compile prompt</Button></div>
  <div id="output" className="bg-white/[.018] p-5 lg:p-7"><div className="mb-4 flex items-center justify-between"><span className="label">02 · COMPILED PROMPT</span><div className="flex items-center gap-2"><Badge className="border-emerald-400/15 bg-emerald-400/[.07] text-[10px] text-emerald-300">QUALITY 94</Badge><Button size="sm" variant="ghost" className="text-xs text-zinc-400" onClick={copy}><Clipboard size={13}/>{copied?"Copied":"Copy"}</Button></div></div><div className="output"><pre>{prompt}</pre></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-[10px] text-zinc-500">{[["Clear","objective"],["5","constraints"],[model,"target"]].map(([a,b])=><div className="metric" key={b}><strong>{a}</strong><span>{b}</span></div>)}</div></div></div></div></section>
  <section id="capabilities" className="border-y border-white/[.06] bg-white/[.018] py-24"><div className="mx-auto max-w-[1180px] px-5"><div className="mb-14 max-w-2xl"><span className="eyebrow">BUILT FOR AI DELIVERY</span><h2 className="mt-4 text-4xl font-medium tracking-tight sm:text-5xl">From idea to governed AI asset.</h2><p className="mt-5 text-zinc-400">Instruxa treats prompts like production code: structured, measurable, portable, and ready for teams.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.08] md:grid-cols-3">{([[Layers3,"Compile, don’t guess","Turn goals, context and constraints into a complete instruction system."],[Zap,"Model-aware optimization","Prepare prompts for every major model without rewriting from scratch."],[ShieldCheck,"Enterprise governance","Versions, approvals, roles, audit trails, and protected knowledge."],[KeyRound,"Hybrid model access","Use included credits or connect provider keys for control and scale."],[Users,"Team prompt registry","Build a shared source of truth instead of losing prompts across chats."],[Command,"Developer-first exports","Copy clean Markdown, JSON, variables, or commit prompts with code."]] as const).map(([Icon,title,body])=><article className="feature" key={title}><Icon size={21}/><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
  <section id="pricing" className="mx-auto max-w-[1240px] px-5 py-28"><div className="mx-auto mb-14 max-w-2xl text-center"><span className="eyebrow">SIMPLE, CONTROLLED SPEND</span><h2 className="mt-4 text-4xl font-medium tracking-tight sm:text-5xl">Start free. Scale on your terms.</h2><p className="mt-5 text-zinc-400">Included credits for convenience. Your own keys for complete provider control.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{plans.map(([name,price,note,features],i)=><article className={`price ${i===1?"featured":""}`} key={name}>{i===1&&<span className="popular">MOST POPULAR</span>}<h3>{name}</h3><p className="mt-1 text-xs text-zinc-500">{note}</p><div className="my-6 flex items-end gap-1"><strong>{price}</strong>{price.startsWith("$")&&<span>/month</span>}</div><Button className={i===1?"glow w-full":"w-full border-white/10 bg-white/[.05]"}>{i===3?"Talk to sales":`Start ${name}`}</Button><ul>{features.map(f=><li key={f}><Check size={13}/>{f}</li>)}</ul></article>)}</div><p className="mt-6 text-center text-xs text-zinc-600">Proposed launch pricing; billing is not active in this preview.</p></section>
  <section className="mx-auto max-w-[1180px] px-5 pb-28"><div className="cta"><div><span className="eyebrow">READY TO BUILD BETTER?</span><h2 className="mt-3 text-3xl font-medium sm:text-4xl">Make every AI interaction intentional.</h2></div><Button size="lg" className="glow">Start building free <ArrowRight size={16}/></Button></div></section><footer className="border-t border-white/[.06]"><div className="mx-auto flex max-w-[1180px] flex-col gap-5 px-5 py-8 text-xs text-zinc-600 sm:flex-row sm:justify-between"><span className="text-zinc-400">Instruxa</span><p>© 2026 Instruxa. Prompt infrastructure for ambitious teams.</p><div className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Security</a></div></div></footer>
 </main>
}
