"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { FolderOpen, LogIn, LogOut, Save, Trash2, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type User={id:string;name:string;email:string};
type Project={id:string;title:string;goal:string;audience:string;tone:string;model:string;compiledPrompt:string;updatedAt?:string};
type Props={draft:Omit<Project,"id"|"title">;onLoad:(project:Project)=>void};
async function request<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,{...options,headers:{"content-type":"application/json",...options?.headers}});const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error||"Request failed");return data}

export function AccountWorkspace({draft,onLoad}:Props){
 const [user,setUser]=useState<User|null>(null),[projects,setProjects]=useState<Project[]>([]),[mode,setMode]=useState<"login"|"register">("register"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[title,setTitle]=useState("My prompt project"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const refresh=useCallback(async()=>{try{const session=await request<{user:User|null}>("/api/auth/session");setUser(session.user);if(session.user){const data=await request<{projects:Project[]}>("/api/projects");setProjects(data.projects)}}catch(e){setMessage(e instanceof Error?e.message:"Unable to load account")}},[]);
 useEffect(()=>{void request<{user:User|null}>("/api/auth/session").then(async session=>{setUser(session.user);if(session.user){const data=await request<{projects:Project[]}>("/api/projects");setProjects(data.projects)}}).catch(e=>setMessage(e instanceof Error?e.message:"Unable to load account"))},[]);
 async function authenticate(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const data=await request<{user:User}>(`/api/auth/${mode}`,{method:"POST",body:JSON.stringify({name,email,password})});setUser(data.user);setPassword("");await refresh();setMessage(mode==="register"?"Account created securely.":"Welcome back.")}catch(e){setMessage(e instanceof Error?e.message:"Authentication failed")}finally{setBusy(false)}}
 async function save(){setBusy(true);setMessage("");try{await request("/api/projects",{method:"POST",body:JSON.stringify({title,...draft})});await refresh();setMessage("Project saved.")}catch(e){setMessage(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}}
 async function remove(projectId:string){if(!confirm("Delete this project permanently?"))return;try{await request(`/api/projects/${projectId}`,{method:"DELETE"});await refresh();setMessage("Project deleted.")}catch(e){setMessage(e instanceof Error?e.message:"Delete failed")}}
 async function logout(){await request("/api/auth/logout",{method:"POST",body:"{}"});setUser(null);setProjects([]);setMessage("Signed out.")}
 return <section id="account" className="account-section"><div className="account-card"><div><span className="eyebrow">ACCOUNT + PROJECT CLOUD</span><h2>{user?`Welcome, ${user.name}`:"Save your prompt workspace"}</h2><p>{user?"Your private projects are attached only to your account.":"Create a free account to save, reopen, and manage prompt projects across devices."}</p></div>
 {!user?<form className="auth-form" onSubmit={authenticate}>{mode==="register"&&<Input aria-label="Name" placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} required minLength={2}/>}<Input aria-label="Email" type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} required/><Input aria-label="Password" type="password" placeholder="Password · minimum 10 characters" value={password} onChange={e=>setPassword(e.target.value)} required minLength={10}/><Button className="glow" disabled={busy}>{mode==="register"?<UserPlus size={15}/>:<LogIn size={15}/>} {busy?"Please wait…":mode==="register"?"Create secure account":"Sign in"}</Button><button type="button" className="mode-link" onClick={()=>setMode(mode==="register"?"login":"register")}>{mode==="register"?"Already registered? Sign in":"New to Instruxa? Create account"}</button></form>:<div className="project-cloud"><div className="save-row"><Input aria-label="Project title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={120}/><Button className="glow" onClick={save} disabled={busy}><Save size={15}/>Save project</Button><Button variant="outline" onClick={logout}><LogOut size={15}/>Sign out</Button></div><div className="project-list">{projects.length===0?<div className="empty-projects"><FolderOpen size={22}/><span>No saved projects yet. Your current draft is ready to save.</span></div>:projects.map(project=><article key={project.id}><button className="project-open" onClick={()=>{onLoad(project);setTitle(project.title);document.getElementById("studio")?.scrollIntoView({behavior:"smooth"})}}><strong>{project.title}</strong><span>{project.goal}</span><small>{project.model}{project.updatedAt?` · ${new Date(project.updatedAt).toLocaleDateString()}`:""}</small></button><button className="project-delete" aria-label={`Delete ${project.title}`} onClick={()=>remove(project.id)}><Trash2 size={15}/></button></article>)}</div></div>}{message&&<p className="account-message" role="status">{message}</p>}</div></section>
}
