"use client";

import { useCallback, useEffect, useState } from "react";
import { ArrowRight, Check, Coins, CreditCard, Crown, LoaderCircle, LockKeyhole, RefreshCw, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";

type Plan={id:"free"|"pro"|"team";name:string;price:number;monthlyCredits:number;maxProjects:number;requestsPerMinute:number;comparisonModels:number;features:string[];checkoutReady:boolean};
type CreditPack={id:string;credits:number;price:number;checkoutReady:boolean};
type Ledger={id:string;amount:number;balanceAfter:number;kind:string;source:string;note:string;createdAt:string};
type Billing={subscription:{planId:"free"|"pro"|"team";status:string;currentPeriodEnd?:string;cancelAtPeriodEnd:boolean;canManage?:boolean};entitlements:Plan;credits:number;plans:Plan[];creditPacks:CreditPack[];ledger:Ledger[];billingConfigured:boolean;billingMode:"disabled"|"test"|"live";migrationRequired:boolean};
const publicPlans:Plan[]=[
 {id:"free",name:"Free",price:0,monthlyCredits:25,maxProjects:3,requestsPerMinute:10,comparisonModels:2,checkoutReady:true,features:["25 starter credits","Encrypted BYOK","3 private projects","Response quality scoring"]},
 {id:"pro",name:"Pro",price:19,monthlyCredits:1000,maxProjects:10000,requestsPerMinute:30,comparisonModels:3,checkoutReady:false,features:["1,000 credits every month","Unlimited projects and versions","3-model Response Lab","Usage intelligence"]},
 {id:"team",name:"Team",price:49,monthlyCredits:5000,maxProjects:10000,requestsPerMinute:60,comparisonModels:3,checkoutReady:false,features:["5,000 credits every month","Everything in Pro","60 executions per minute","Team controls arriving in beta"]},
];

async function request<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"content-type":"application/json",...options?.headers}});const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error||"Billing request failed");return data}

export function BillingCenter(){
 const [data,setData]=useState<Billing|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);setMessage("");try{setData(await request<Billing>("/api/billing"))}catch(error){const text=error instanceof Error?error.message:"Billing unavailable";if(text.toLowerCase().includes("authentication"))setData(null);else setMessage(text)}finally{setLoading(false)}},[]);
 useEffect(()=>{let active=true;request<Billing>("/api/billing").then(next=>{if(active)setData(next)}).catch(error=>{if(!active)return;const text=error instanceof Error?error.message:"Billing unavailable";if(text.toLowerCase().includes("authentication"))setData(null);else setMessage(text)}).finally(()=>{if(active)setLoading(false)});const sync=()=>void load();window.addEventListener("instruxa-auth-changed",sync);return()=>{active=false;window.removeEventListener("instruxa-auth-changed",sync)}},[load]);
 async function checkout(payload:Record<string,string>){setBusy(payload.planId||payload.packId||"checkout");setMessage("");try{const result=await request<{url:string}>("/api/billing/checkout",{method:"POST",headers:{"x-idempotency-key":crypto.randomUUID()},body:JSON.stringify(payload)});window.location.assign(result.url)}catch(error){setMessage(error instanceof Error?error.message:"Checkout could not start")}finally{setBusy("")}}
 async function portal(){setBusy("portal");setMessage("");try{const result=await request<{url:string}>("/api/billing/portal",{method:"POST",body:"{}"});window.location.assign(result.url)}catch(error){setMessage(error instanceof Error?error.message:"Billing portal could not open")}finally{setBusy("")}}
 const active=data?.subscription.planId??"free",plans=data?.plans??publicPlans,signedIn=Boolean(data);
 return <section id="billing" className="billing-section"><div className="billing-head"><div><span className="eyebrow">PLANS + CREDITS</span><h2>Scale usage without losing control.</h2><p>Subscription entitlements, included model credits, encrypted BYOK, and an auditable balance history in one secure account center.</p></div>{data&&<div className="billing-balance"><Coins size={18}/><span><small>AVAILABLE BALANCE</small><strong>{data.credits.toLocaleString()} credits</strong></span>{data.subscription.canManage&&<Button size="sm" variant="outline" onClick={portal} disabled={busy==="portal"}>{busy==="portal"?<LoaderCircle className="runner-spinner" size={13}/>:<CreditCard size={13}/>}Manage</Button>}</div>}</div>
 <div className="billing-plans">{plans.map(plan=><article className={`${plan.id==="pro"?"recommended ":""}${signedIn&&active===plan.id?"current":""}`} key={plan.id}>{plan.id==="pro"&&<span className="plan-ribbon"><Sparkles size={11}/>RECOMMENDED</span>}<header><span>{plan.id==="team"?<Crown/>:plan.id==="pro"?<Zap/>:<ShieldCheck/>}</span><div><h3>{plan.name}</h3><small>{plan.monthlyCredits.toLocaleString()} included credits</small></div></header><div className="plan-price"><strong>${plan.price}</strong><span>{plan.price?"/ month":"forever"}</span></div><ul>{plan.features.map(feature=><li key={feature}><Check size={13}/>{feature}</li>)}</ul>{!signedIn?<Button asChild className={plan.id==="pro"?"glow plan-button":"plan-button"} variant={plan.id==="pro"?"default":"outline"}><a href="#account">{plan.id==="free"?"Start free":`Sign in for ${plan.name}`}<ArrowRight size={13}/></a></Button>:active===plan.id?<Button disabled className="plan-button"><Check size={14}/>Current plan</Button>:plan.id==="free"?<Button disabled variant="outline" className="plan-button">Free foundation</Button>:data?.subscription.canManage?<Button className="plan-button" variant="outline" disabled={Boolean(busy)} onClick={portal}>{busy==="portal"?<LoaderCircle className="runner-spinner" size={14}/>:<CreditCard size={14}/>} Change in billing portal</Button>:<Button className={plan.id==="pro"?"glow plan-button":"plan-button"} variant={plan.id==="pro"?"default":"outline"} disabled={Boolean(busy)||!plan.checkoutReady} onClick={()=>checkout({kind:"subscription",planId:plan.id})}>{busy===plan.id?<LoaderCircle className="runner-spinner" size={14}/>:<CreditCard size={14}/>} {plan.checkoutReady?`Choose ${plan.name}`:"Checkout setup pending"}</Button>}<footer><span>{plan.requestsPerMinute} runs/min</span><span>{plan.maxProjects>=10000?"Unlimited":plan.maxProjects} projects</span></footer></article>)}</div>
 <p className="pricing-disclosure">Launch pricing · {data?.billingMode==="test"?"Stripe test mode is active; no real charge is created.":data?.billingMode==="live"?"Secure live checkout is active.":"Secure checkout remains disabled until Stripe test-mode verification is complete."}</p>
 {!data?<div className="billing-locked"><LockKeyhole size={26}/><strong>{loading?"Checking your account…":"Sign in to manage plans and credits"}</strong><span>Checkout, balances, and invoices stay connected to your private Instruxa account.</span><a href="#account">Go to secure sign in <ArrowRight size={13}/></a></div>:<>
  <div className="credit-store"><div><span className="eyebrow">ON-DEMAND CAPACITY</span><h3>Top up only when you need it.</h3><p>Purchased credits do not replace BYOK. They simply add convenient platform capacity to your existing balance.</p></div><div className="credit-packs">{data?.creditPacks.map(pack=><button key={pack.id} disabled={Boolean(busy)||!pack.checkoutReady} onClick={()=>checkout({kind:"credits",packId:pack.id})}><Coins size={16}/><span><strong>{pack.credits.toLocaleString()}</strong><small>credits</small></span><b>${pack.price}</b>{busy===pack.id&&<LoaderCircle className="runner-spinner" size={14}/>}</button>)}</div></div>
  <div className="ledger-panel"><header><div><RefreshCw size={14}/><strong>Credit ledger</strong></div><Button size="sm" variant="ghost" onClick={load} disabled={loading}><RefreshCw className={loading?"runner-spinner":""} size={12}/>Refresh</Button></header>{data?.ledger.length?<div className="ledger-list">{data.ledger.map(entry=><div key={entry.id}><span className={entry.amount>=0?"positive":"negative"}>{entry.amount>=0?"+":""}{entry.amount}</span><p><strong>{entry.note}</strong><small>{entry.source} · {new Date(entry.createdAt).toLocaleString()}</small></p><b>{entry.balanceAfter} balance</b></div>)}</div>:<div className="ledger-empty"><Coins size={20}/><span>Your purchases and recurring plan grants will appear here.</span></div>}</div>
 </>}
 {data?.migrationRequired&&<p className="billing-notice">Apply <code>migrations/0005_monetization.sql</code> to activate subscription records and the credit ledger.</p>}{message&&<p className="billing-message" role="status">{message}</p>}
 </section>
}
