"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Bot, CheckCircle2, Clipboard, KeyRound, Play, ShieldCheck, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Provider="openai"|"anthropic"|"gemini";
type Config={keys:Array<{provider:Provider;keyLast4:string}>;credits:number;platform:Record<Provider,boolean>;defaults:Record<Provider,string>};
const labels:Record<Provider,string>={openai:"OpenAI",anthropic:"Claude",gemini:"Gemini"};
async function call<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,{...options,headers:{"content-type":"application/json",...options?.headers}});const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error||"Request failed");return data}

export function ModelRunner({prompt}:{prompt:string}){
 const [config,setConfig]=useState<Config|null>(null),[provider,setProvider]=useState<Provider>("openai"),[mode,setMode]=useState<"byok"|"included">("byok"),[model,setModel]=useState("gpt-5-mini"),[apiKey,setApiKey]=useState(""),[output,setOutput]=useState(""),[usage,setUsage]=useState<{inputTokens:number;outputTokens:number}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{setConfig(await call<Config>("/api/ai/config"))}catch(e){const text=e instanceof Error?e.message:"Sign in to use the model gateway";if(!text.toLowerCase().includes("authentication"))setMessage(text)}},[]);
 useEffect(()=>{void call<Config>("/api/ai/config").then(setConfig).catch(e=>{const text=e instanceof Error?e.message:"Sign in to use the model gateway";if(!text.toLowerCase().includes("authentication"))setMessage(text)})},[]);\n useEffect(()=>{const sync=()=>void load();window.addEventListener("instruxa-auth-changed",sync);return()=>window.removeEventListener("instruxa-auth-changed",sync)},[load]);
 const connected=useMemo(()=>config?.keys.find(x=>x.provider===provider),[config,provider]);
 async function saveKey(){setBusy(true);setMessage("");try{await call("/api/ai/keys",{method:"POST",body:JSON.stringify({provider,apiKey})});setApiKey("");await load();setMessage(`${labels[provider]} key encrypted and connected.`)}catch(e){setMessage(e instanceof Error?e.message:"Key connection failed")}finally{setBusy(false)}}
 async function removeKey(){if(!confirm(`Remove your ${labels[provider]} key?`))return;setBusy(true);try{await call(`/api/ai/keys/${provider}`,{method:"DELETE"});await load();setMessage("Key removed.")}catch(e){setMessage(e instanceof Error?e.message:"Removal failed")}finally{setBusy(false)}}
 async function run(){setBusy(true);setMessage("");setOutput("");setUsage(null);try{const result=await call<{text:string;inputTokens:number;outputTokens:number;credits:number}>("/api/ai/generate",{method:"POST",body:JSON.stringify({provider,model,mode,prompt})});setOutput(result.text);setUsage({inputTokens:result.inputTokens,outputTokens:result.outputTokens});if(config)setConfig({...config,credits:result.credits});setMessage("Model response completed securely.")}catch(e){setMessage(e instanceof Error?e.message:"Generation failed")}finally{setBusy(false)}}
 return <section id="model-runner" className="runner-section"><div className="runner-head"><div><span className="eyebrow">SECURE MULTI-MODEL GATEWAY</span><h2>Run the prompt against real AI.</h2><p>Your key is encrypted before storage, never returned to the browser, and only decrypted inside the Worker for your selected provider.</p></div><div className="credit-chip"><ShieldCheck size={15}/><strong>{config?.credits??"—"}</strong><span>included credits</span></div></div>
 <div className="runner-grid"><div className="runner-controls"><label>Provider<select value={provider} onChange={e=>setProvider(e.target.value as Provider)}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Model<Input value={model} onChange={e=>setModel(e.target.value)} maxLength={120}/></label><div className="access-tabs"><button className={mode==="byok"?"active":""} onClick={()=>setMode("byok")}><KeyRound size={14}/>Own API key</button><button className={mode==="included"?"active":""} onClick={()=>setMode("included")}><Bot size={14}/>Included credits</button></div>{mode==="byok"&&<div className="key-box">{connected?<div className="connected-key"><CheckCircle2 size={16}/><span>{labels[provider]} connected ·•••• {connected.keyLast4}</span><Button size="sm" variant="ghost" onClick={removeKey} disabled={busy}><Trash2 size={14}/></Button></div>:<><Input type="password" autoComplete="off" placeholder={`Paste your ${labels[provider]} API key`} value={apiKey} onChange={e=>setApiKey(e.target.value)}/><Button onClick={saveKey} disabled={busy||apiKey.length<16}><KeyRound size={14}/>Encrypt & connect</Button></>}</div>}{mode==="included"&&!config?.platform[provider]&&<p className="runner-notice">Included {labels[provider]} access is not funded yet. BYOK is available without platform markup.</p>}<Button className="glow h-11" onClick={run} disabled={busy||!prompt||!config}><Play size={15}/>{busy?"Running securely…":"Run compiled prompt"}</Button>{message&&<p className="runner-message" role="status">{message}</p>}</div>
 <div className="runner-output"><div className="runner-output-head"><span>MODEL RESPONSE</span>{usage&&<small>{usage.inputTokens} input · {usage.outputTokens} output tokens</small>}<Button size="sm" variant="ghost" disabled={!output} onClick={()=>navigator.clipboard.writeText(output)}><Clipboard size={14}/>Copy</Button></div>{output?<pre>{output}</pre>:<div className="runner-empty"><Bot size={30}/><strong>Ready for a real model run</strong><span>Connect a provider key or choose included access when available.</span></div>}</div></div></section>
}
